import { useState } from 'react';
import { useLocation } from 'wouter';
import { ArrowRight, Check, KeyRound, Mail, ShieldCheck, ScanSearch } from 'lucide-react';
import { useCompletePasswordReset, useHealthCheck, useLogin, useRegister, useRequestPasswordReset } from '@workspace/api-client-react';

type Mode = 'login' | 'register' | 'forgot' | 'complete';
export default function AuthPage() {
  const [, setLocation] = useLocation();
  const [mode, setMode] = useState<Mode>('login');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [token, setToken] = useState(''); const [message, setMessage] = useState('');
  const login = useLogin(); const register = useRegister(); const forgot = useRequestPasswordReset(); const complete = useCompletePasswordReset(); const health = useHealthCheck({ query: { queryKey: ['/api/healthz'] } });
  const busy = login.isPending || register.isPending || forgot.isPending || complete.isPending;
  const submit = (e: React.FormEvent) => { e.preventDefault(); setMessage(''); if (mode === 'login') login.mutate({ data: { email, password } }, { onSuccess: () => setLocation('/dashboard'), onError: (error) => setMessage(error instanceof Error ? error.message : 'Sign-in was not accepted.') }); if (mode === 'register') register.mutate({ data: { email, password } }, { onSuccess: () => setMessage('Account request received. An administrator will review it shortly.'), onError: () => setMessage('Could not submit this account request.') }); if (mode === 'forgot') forgot.mutate({ data: { email } }, { onSuccess: () => setMessage('If that address is registered, reset instructions are on their way.') }); if (mode === 'complete') complete.mutate({ data: { token, newPassword: password } }, { onSuccess: () => { setMode('login'); setMessage('Password updated. You can sign in now.'); } }); };
  const title = mode === 'login' ? 'Welcome back, operator.' : mode === 'register' ? 'Request access.' : mode === 'forgot' ? 'Recover your access.' : 'Set a new password.';
  return <div className="min-h-[100dvh] bg-background app-grid lg:grid lg:grid-cols-[minmax(360px,43%)_1fr]">
    <section className="relative hidden overflow-hidden bg-primary p-12 text-primary-foreground lg:flex lg:flex-col lg:justify-between">
      <div className="absolute -right-32 -top-32 h-[470px] w-[470px] rounded-full border border-primary-foreground/10" /><div className="absolute -right-8 top-[-5rem] h-[330px] w-[330px] rounded-full border border-primary-foreground/10" /><div className="absolute bottom-20 left-[-10rem] h-[450px] w-[450px] rounded-full border border-primary-foreground/10" />
      <div className="relative"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary-foreground text-primary"><ScanSearch size={23} /></span><div><p className="font-bold">Ultra AutoDetector</p><p className="font-mono-ui text-[9px] uppercase tracking-[.2em] text-primary-foreground/60">admin console</p></div></div><div className="mt-28 max-w-md"><p className="font-mono-ui text-[10px] uppercase tracking-[.22em] text-primary-foreground/60">Native Android detection · 0.2</p><h2 className="mt-5 text-5xl font-bold leading-[1.03] tracking-[-.06em]">See the signal.<br/><span className="text-[hsl(var(--accent))]">Act with certainty.</span></h2><p className="mt-7 max-w-sm text-sm leading-7 text-primary-foreground/70">A focused operations room for account access, screen templates, and the decisions that keep your detection fleet dependable.</p></div></div>
      <div className="relative flex items-center gap-4 text-xs text-primary-foreground/70"><ShieldCheck size={17} className="text-[hsl(var(--accent))]" /><span>Protected operator access</span><span className="ml-auto font-mono-ui text-[10px]">{health.isError ? 'OFFLINE' : 'SYSTEM READY'}</span></div>
    </section>
    <section className="flex min-h-[100dvh] items-center justify-center p-5 sm:p-10"><div className="w-full max-w-[430px] animate-rise">
      <div className="mb-10 flex items-center gap-3 lg:hidden"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary text-primary-foreground"><ScanSearch size={20} /></span><div><p className="font-bold">Ultra AutoDetector</p><p className="font-mono-ui text-[9px] uppercase tracking-widest text-muted-foreground">admin console</p></div></div>
      <div className="mb-8"><p className="mb-3 font-mono-ui text-[10px] font-bold uppercase tracking-[.2em] text-primary">{mode === 'login' ? 'Administrator sign-in' : 'Account access'}</p><h1 className="text-3xl font-bold tracking-[-.05em]">{title}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{mode === 'login' ? 'Use your administrator credentials to enter the operations room.' : mode === 'register' ? 'Submit an account request for administrator review.' : 'We will help you get back into the console securely.'}</p></div>
      <form onSubmit={submit} className="space-y-5">
        {mode !== 'complete' && <label className="block"><span className="mb-2 block text-xs font-bold">Email address</span><div className="relative"><Mail size={16} className="absolute left-3 top-3.5 text-muted-foreground" /><input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="operator@company.com" className="focus-ring h-11 w-full rounded-lg border border-input bg-card pl-10 pr-3 text-sm outline-none transition-colors focus:border-primary" data-testid="input-auth-email" /></div></label>}
        {(mode === 'login' || mode === 'register' || mode === 'complete') && <label className="block"><span className="mb-2 block text-xs font-bold">{mode === 'complete' ? 'New password' : 'Password'}</span><div className="relative"><KeyRound size={16} className="absolute left-3 top-3.5 text-muted-foreground" /><input required minLength={8} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="8 characters minimum" className="focus-ring h-11 w-full rounded-lg border border-input bg-card pl-10 pr-3 text-sm outline-none transition-colors focus:border-primary" data-testid="input-auth-password" /></div></label>}
        {mode === 'complete' && <label className="block"><span className="mb-2 block text-xs font-bold">Reset token</span><input required minLength={20} value={token} onChange={e => setToken(e.target.value)} placeholder="Paste your reset token" className="focus-ring h-11 w-full rounded-lg border border-input bg-card px-3 font-mono-ui text-xs outline-none focus:border-primary" data-testid="input-reset-token" /></label>}
        {message && <div className="rounded-lg border border-primary/15 bg-primary/5 p-3 text-xs leading-5 text-primary" data-testid="status-auth-message"><Check size={14} className="mr-2 inline" />{message}</div>}
        <button disabled={busy} type="submit" className="group flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-primary text-sm font-bold text-primary-foreground transition-transform hover:-translate-y-0.5 disabled:cursor-wait disabled:opacity-60" data-testid="button-auth-submit">{busy ? 'Working…' : mode === 'login' ? 'Enter console' : mode === 'register' ? 'Submit request' : mode === 'forgot' ? 'Send instructions' : 'Update password'}<ArrowRight size={16} className="transition-transform group-hover:translate-x-1" /></button>
      </form>
      <div className="mt-7 flex flex-wrap gap-x-4 gap-y-2 text-xs font-semibold text-muted-foreground">{mode === 'login' && <><button onClick={() => setMode('forgot')} className="hover:text-primary" data-testid="button-forgot-password">Forgot password?</button><button onClick={() => setMode('register')} className="hover:text-primary" data-testid="button-register">Request an account</button></>}{mode === 'forgot' && <><button onClick={() => setMode('complete')} className="hover:text-primary" data-testid="button-have-reset-token">I have a reset token</button><button onClick={() => setMode('login')} className="hover:text-primary" data-testid="button-back-login">Back to sign in</button></>}{(mode === 'register' || mode === 'complete') && <button onClick={() => setMode('login')} className="hover:text-primary" data-testid="button-back-to-login">Back to sign in</button>}</div>
      <p className="mt-12 font-mono-ui text-[9px] uppercase tracking-[.14em] text-muted-foreground/70">Session encrypted · API {health.isError ? 'unavailable' : 'available'}</p>
    </div></section>
  </div>;
}
