import { Link } from 'wouter';
import { ArrowUpRight, CheckCircle2, Clock3, FileScan, Plus, ShieldAlert, Users, Activity, ScanSearch } from 'lucide-react';
import { useGetCurrentUser, useListAuditLogs, useListTemplates, useListUsers, getListAuditLogsQueryKey, getListTemplatesQueryKey, getListUsersQueryKey } from '@workspace/api-client-react';
import { PageHeading, LoadingRows, ErrorState } from '@/components/app-shell';

const fmt = (date?: string | null) => date ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(date)) : 'No expiry';
export default function Dashboard() {
  const users = useListUsers({ query: { queryKey: getListUsersQueryKey() } }); const templates = useListTemplates({ query: { queryKey: getListTemplatesQueryKey() } }); const logs = useListAuditLogs({ query: { queryKey: getListAuditLogsQueryKey() } }); const me = useGetCurrentUser();
  if (users.isLoading || templates.isLoading || logs.isLoading) return <><PageHeading eyebrow="Operations / overview" title="Good morning, operator." description="Loading your account signal and detection fleet." /><LoadingRows count={5} /></>;
  if (users.isError || templates.isError || logs.isError) return <ErrorState retry={() => { users.refetch(); templates.refetch(); logs.refetch(); }} />;
  const list = users.data?.users ?? []; const active = list.filter(u => u.status === 'active').length; const pending = list.filter(u => u.status === 'pending').length; const licensed = list.filter(u => u.expirationAt && new Date(u.expirationAt) > new Date()).length; const templateList = templates.data?.templates ?? []; const logList = logs.data?.logs ?? [];
  return <div className="animate-rise"><PageHeading eyebrow="Operations / overview" title="Good morning, operator." description={`A clear view of ${me.data?.user?.email ?? 'your'} access surface and detection fleet.`} action={<Link href="/users" className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-xs font-bold text-primary-foreground shadow-sm transition-transform hover:-translate-y-0.5" data-testid="link-review-accounts">Review accounts <ArrowUpRight size={15} /></Link>} />
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      {[['Total accounts', list.length, Users, 'bg-primary/10 text-primary', '/users'], ['Active licenses', licensed, CheckCircle2, 'bg-[hsl(var(--accent)/.15)] text-[hsl(var(--accent))]', '/users'], ['Awaiting review', pending, Clock3, 'bg-amber-500/10 text-amber-700', '/users'], ['Active templates', templateList.filter(t => t.isActive).length, FileScan, 'bg-secondary text-foreground', '/templates']].map(([label, value, Icon, color, href], i) => <Link href={href as string} key={label as string} className={`group rounded-2xl border border-border bg-card p-5 quiet-shadow animate-rise delay-${i + 1}`} data-testid={`card-stat-${String(label).toLowerCase().replaceAll(' ', '-')}`}><div className="flex items-start justify-between"><span className={`grid h-9 w-9 place-items-center rounded-lg ${color}`}><Icon size={18} /></span><ArrowUpRight size={16} className="text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100" /></div><p className="mt-6 text-3xl font-bold tracking-[-.05em]">{value}</p><p className="mt-1 text-xs font-semibold text-muted-foreground">{label}</p></Link>)}
    </section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-2xl border border-border bg-card p-6 quiet-shadow"><div className="mb-6 flex items-start justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-primary">Access queue</p><h2 className="mt-1 text-lg font-bold tracking-[-.03em]">Accounts needing attention</h2></div><Link href="/users" className="text-xs font-bold text-primary hover:underline" data-testid="link-view-all-accounts">View all</Link></div>{list.filter(u => u.status === 'pending' || u.status === 'expired').slice(0, 5).map(user => <div key={user.id} className="flex items-center gap-3 border-t border-border py-3.5" data-testid={`row-attention-${user.id}`}><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-secondary text-[10px] font-bold text-primary">{user.email.slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{user.email}</p><p className="text-[11px] text-muted-foreground">Created {fmt(user.createdAt)}</p></div><span className={`rounded-full px-2.5 py-1 font-mono-ui text-[9px] font-bold uppercase ${user.status === 'pending' ? 'bg-amber-500/10 text-amber-700' : 'bg-destructive/10 text-destructive'}`}>{user.status}</span></div>)}{list.filter(u => u.status === 'pending' || u.status === 'expired').length === 0 && <p className="border-t border-border pt-5 text-sm text-muted-foreground">No accounts need attention right now.</p>}</div>
      <div className="rounded-2xl border border-border bg-card p-6 quiet-shadow"><div className="mb-6 flex items-start justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-primary">Detection fleet</p><h2 className="mt-1 text-lg font-bold tracking-[-.03em]">Template coverage</h2></div><Link href="/templates" className="text-xs font-bold text-primary hover:underline" data-testid="link-manage-templates">Manage</Link></div><div className="flex items-center gap-7 border-b border-border pb-5"><div className="relative grid h-28 w-28 place-items-center rounded-full" style={{ background: `conic-gradient(hsl(var(--primary)) ${templateList.length ? (templateList.filter(t => t.isActive).length / templateList.length) * 360 : 0}deg, hsl(var(--secondary)) 0deg)` }}><div className="grid h-[88px] w-[88px] place-items-center rounded-full bg-card"><span className="text-2xl font-bold">{templateList.filter(t => t.isActive).length}</span></div></div><div><p className="text-sm font-bold">Active templates</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{templateList.length ? `${templateList.filter(t => t.isActive).length} of ${templateList.length} templates are available to the Android detector.` : 'No templates published yet.'}</p></div></div><div className="mt-5 space-y-3">{templateList.slice(0, 3).map(t => <div className="flex items-center gap-3" key={t.id} data-testid={`row-template-summary-${t.id}`}><span className={`h-2 w-2 rounded-full ${t.isActive ? 'bg-[hsl(var(--accent))]' : 'bg-muted-foreground/30'}`} /><span className="flex-1 truncate text-xs font-semibold">{t.name}</span><span className="font-mono-ui text-[10px] text-muted-foreground">{Math.round(t.confidence * 100)}%</span></div>)}</div></div>
    </section>
    <section className="mt-6 rounded-2xl border border-border bg-card p-6 quiet-shadow"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-primary">Trace / latest</p><h2 className="mt-1 text-lg font-bold tracking-[-.03em]">Recent activity</h2></div><Link href="/activity" className="text-xs font-bold text-primary hover:underline" data-testid="link-view-activity">Full audit log</Link></div><div className="grid gap-x-8 md:grid-cols-2">{logList.slice(0, 6).map(log => <div className="flex gap-3 border-t border-border py-3" key={log.id} data-testid={`row-dashboard-log-${log.id}`}><span className="mt-1 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-secondary text-primary"><Activity size={12} /></span><div className="min-w-0"><p className="text-xs font-semibold">{log.action.replaceAll('_', ' ')}</p><p className="mt-1 font-mono-ui text-[9px] text-muted-foreground">{fmt(log.createdAt)} · {log.targetUserId ? `account ${log.targetUserId.slice(0, 8)}` : 'system'}</p></div></div>)}</div></section>
  </div>;
}
