import { useMemo, useState } from 'react';
import { Search, SlidersHorizontal, MoreHorizontal, CheckCircle2, XCircle, CalendarPlus, UserRound, X } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { getListUsersQueryKey, useGrantLicense, useListUsers, useRejectUser } from '@workspace/api-client-react';
import { PageHeading, LoadingRows, ErrorState, EmptyState } from '@/components/app-shell';

const date = (d?: string | null) => d ? new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '—';
export default function UsersPage() {
  const queryClient = useQueryClient(); const query = useListUsers({ query: { queryKey: getListUsersQueryKey() } }); const grant = useGrantLicense(); const reject = useRejectUser(); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [selected, setSelected] = useState<string | null>(null); const [days, setDays] = useState('30'); const [notice, setNotice] = useState('');
  const users = useMemo(() => (query.data?.users ?? []).filter(u => (status === 'all' || u.status === status) && u.email.toLowerCase().includes(search.toLowerCase())), [query.data, search, status]);
  const refresh = () => queryClient.invalidateQueries({ queryKey: getListUsersQueryKey() });
  const act = (kind: 'grant' | 'reject', id: string) => { setNotice(''); if (kind === 'grant') grant.mutate({ id, data: { days: Number(days) } }, { onSuccess: () => { setNotice('License updated.'); setSelected(null); refresh(); }, onError: () => setNotice('License action could not be completed.') }); else reject.mutate({ id }, { onSuccess: () => { setNotice('Account rejected.'); setSelected(null); refresh(); }, onError: () => setNotice('Rejection could not be completed.') }); };
  return <div className="animate-rise"><PageHeading eyebrow="Workspace / accounts" title="Account access" description="Review operators, issue licenses, and keep the access surface intentional." action={<div className="flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-xs font-semibold text-muted-foreground"><UserRound size={15} className="text-primary" />{query.data?.users.length ?? 0} accounts</div>} />
    <div className="mb-5 flex flex-col gap-3 rounded-2xl border border-border bg-card p-3 quiet-shadow sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-muted-foreground" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search by email…" className="h-10 w-full rounded-lg bg-secondary/60 pl-9 pr-3 text-sm outline-none ring-0 placeholder:text-muted-foreground focus:bg-secondary" data-testid="input-search-users" /></div><div className="flex items-center gap-2"><SlidersHorizontal size={15} className="ml-2 text-muted-foreground" /><select value={status} onChange={e => setStatus(e.target.value)} className="h-10 rounded-lg bg-secondary/60 px-3 text-xs font-bold outline-none" data-testid="select-user-status"><option value="all">All statuses</option><option value="pending">Pending</option><option value="active">Active</option><option value="expired">Expired</option><option value="rejected">Rejected</option></select></div></div>
    {notice && <div className="mb-4 rounded-lg border border-primary/20 bg-primary/5 px-4 py-3 text-xs font-semibold text-primary" data-testid="status-user-action">{notice}</div>}
    {query.isLoading ? <LoadingRows count={6} /> : query.isError ? <ErrorState retry={() => query.refetch()} /> : users.length === 0 ? <EmptyState title="No matching accounts" description={search ? 'Try a different email or clear the search.' : 'New account requests will appear here for review.'} /> : <div className="overflow-hidden rounded-2xl border border-border bg-card quiet-shadow"><div className="hidden grid-cols-[1.7fr_110px_145px_135px_92px] gap-4 border-b border-border bg-secondary/45 px-5 py-3 font-mono-ui text-[9px] font-bold uppercase tracking-[.15em] text-muted-foreground md:grid"><span>Account</span><span>Status</span><span>License expiry</span><span>Joined</span><span className="text-right">Actions</span></div>{users.map(user => <div key={user.id} className="grid gap-3 border-b border-border px-5 py-4 last:border-0 md:grid-cols-[1.7fr_110px_145px_135px_92px] md:items-center md:gap-4" data-testid={`row-user-${user.id}`}><div className="flex items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-secondary text-xs font-bold text-primary">{user.email.slice(0, 2).toUpperCase()}</div><div className="min-w-0"><p className="truncate text-sm font-bold">{user.email}</p><p className="font-mono-ui text-[9px] uppercase tracking-wider text-muted-foreground">{user.role} · {user.id.slice(0, 8)}</p></div></div><div><span className={`rounded-full px-2 py-1 font-mono-ui text-[9px] font-bold uppercase ${user.status === 'active' ? 'bg-[hsl(var(--accent)/.15)] text-[hsl(var(--accent))]' : user.status === 'pending' ? 'bg-amber-500/10 text-amber-700' : user.status === 'rejected' ? 'bg-destructive/10 text-destructive' : 'bg-secondary text-muted-foreground'}`} data-testid={`status-user-${user.id}`}>{user.status}</span></div><div className="text-xs font-semibold text-muted-foreground md:text-foreground">{date(user.expirationAt)}</div><div className="text-xs text-muted-foreground">{date(user.createdAt)}</div><div className="flex justify-end gap-1"><button title="Grant or extend license" onClick={() => setSelected(user.id)} className="rounded-lg p-2 text-primary hover:bg-primary/10" data-testid={`button-grant-license-${user.id}`}><CalendarPlus size={16} /></button>{user.status === 'pending' && <button title="Reject account" onClick={() => act('reject', user.id)} disabled={reject.isPending} className="rounded-lg p-2 text-destructive hover:bg-destructive/10" data-testid={`button-reject-user-${user.id}`}><XCircle size={16} /></button>}<button title="More actions" className="rounded-lg p-2 text-muted-foreground hover:bg-secondary" data-testid={`button-user-more-${user.id}`}><MoreHorizontal size={16} /></button></div></div>)}</div>}
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/25 p-5" onMouseDown={e => e.currentTarget === e.target && setSelected(null)}><div className="w-full max-w-sm rounded-2xl border border-border bg-card p-6 shadow-2xl animate-rise"><div className="flex items-start justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-primary">License control</p><h2 className="mt-1 text-xl font-bold">Grant access</h2><p className="mt-2 text-sm text-muted-foreground">Choose how long this account should remain active.</p></div><button onClick={() => setSelected(null)} className="rounded-md p-1 text-muted-foreground hover:bg-secondary" data-testid="button-close-license-dialog"><X size={17} /></button></div><label className="mt-6 block"><span className="mb-2 block text-xs font-bold">License duration</span><select value={days} onChange={e => setDays(e.target.value)} className="h-11 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-primary" data-testid="select-license-days"><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">365 days</option></select></label><button onClick={() => act('grant', selected)} disabled={grant.isPending} className="mt-6 flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-primary text-sm font-bold text-primary-foreground disabled:opacity-60" data-testid="button-confirm-license">{grant.isPending ? 'Updating…' : 'Grant / extend license'}<CheckCircle2 size={15} /></button></div></div>}
  </div>;
}
